volumes:
  postgresql-data:
  redis-data:

networks:
  parking-net:
    external: true

services:

  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    depends_on:
      - mosquitto
      - redis
      - postgresql
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgresql
    networks:
      - parking-net
    volumes:
      - ./config/chirpstack:/etc/chirpstack
    ports:
      - "8080:8080"

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=us915/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=us915/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=us915/gateway/{{ .GatewayID }}/command/#
    networks:
      - parking-net
    volumes:
      - "./config/bridge:/etc/chirpstack-gateway-bridge"
    ports:
      - "1700:1700/udp"

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    networks:
      - parking-net
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto:/mosquitto/config

  redis:
    networks:
      - parking-net
    image: redis:7-alpine
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    restart: unless-stopped
    volumes:
      - redis-data:/data
  
  postgresql:
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
      - parking-net
    environment:
      - POSTGRES_DB=chirpstack
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
    volumes:
      - ./config/postgresql:/docker-entrypoint-initdb.d
      - postgresql-data:/var/lib/postgresql/data
