services:
  server:
    image: parking
    ports:
      - "3000:3000"
    networks:
      - parking-net
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:7.4.2-alpine
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - parking-net
  postgres:
    image: docker.io/postgres:17.3-bookworm
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pas-website
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parking-net

volumes:
  redis-data:
  postgres_data:

networks:
  parking-net: